"""
Database connection pool, schema management, and data helpers for RAGScope.

This module is the single place that creates and owns the asyncpg connection
pool. All other modules that need a database connection call get_pool() here
rather than creating their own connections.

The pool is initialised lazily on first use so the application can import
this module at startup without immediately requiring a reachable database --
useful during local development when the database container may not be up yet.

Two tables are managed here:
  benchmark_runs -- one row per evaluation run, tracks status and metrics.
  corpus_chunks  -- stores pre-embedded text chunks indexed by corpus_hash.
"""

import json

import asyncpg
from pgvector.asyncpg import register_vector

from backend.core.config import settings


# Module-level pool singleton. None until get_pool() is called for the first
# time. Declared at module scope so the same pool is reused across all calls.
_pool: asyncpg.Pool | None = None


async def _init_connection(conn: asyncpg.Connection) -> None:
    """
    Register JSONB type codecs on each newly created connection.

    asyncpg does not automatically marshal Python dicts to/from Postgres JSONB.
    This function is passed as the `init` argument to create_pool() so it runs
    once for every connection the pool creates. After this, code can pass a
    Python dict to a JSONB parameter and receive a dict back from a JSONB column
    without manually calling json.dumps / json.loads.

    Parameters
    ----------
    conn : asyncpg.Connection
        Freshly created connection being initialised by the pool.
    """
    await conn.set_type_codec(
        "jsonb",
        encoder=json.dumps,
        decoder=json.loads,
        schema="pg_catalog",
    )
    # Register the pgvector codec so Python lists are accepted as vector(1536)
    # parameters and vector columns are returned as numpy arrays.
    await register_vector(conn)


async def get_pool() -> asyncpg.Pool:
    """
    Return the shared asyncpg connection pool, creating it on first call.

    Subsequent calls return the same pool object without re-connecting.
    The pool size defaults to asyncpg's built-in minimum/maximum (10 connections)
    which is appropriate for the expected concurrency on Render's free tier.

    Returns
    -------
    asyncpg.Pool
        Ready-to-use connection pool pointed at the configured database URL.
    """
    global _pool
    if _pool is None:
        _pool = await asyncpg.create_pool(
            settings.supabase_url,
            init=_init_connection,
        )
    return _pool


async def close_pool() -> None:
    """
    Gracefully close all connections in the pool.

    Called during application shutdown (via a FastAPI lifespan event) so
    Postgres does not see abrupt disconnects. Safe to call even if the pool
    was never initialised.
    """
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None


async def create_tables() -> None:
    """
    Create all application tables if they do not already exist.

    Idempotent -- safe to call on every application startup. The IF NOT EXISTS
    clause means it does nothing if the schema is already in place.

    Column design notes:
    - id is UUID generated by Postgres so the application never needs to supply
      one, and IDs are globally unique with no coordination needed.
    - retrieval_params / chunker_params / compression_params are JSONB so new
      strategy parameters can be stored without altering the schema.
    - retrieved_chunks is JSONB so the full result list (with scores and
      metadata) can be stored and retrieved as a structured document.
    - Metric columns (faithfulness, context_utilization, answer_relevancy) are
      nullable floats -- they are NULL while the run is in progress and only
      set when status transitions to 'completed'.
    """
    pool = await get_pool()
    async with pool.acquire() as conn:
        # Enable the pgvector extension before creating tables that use it.
        # IF NOT EXISTS makes this idempotent.
        await conn.execute("CREATE EXTENSION IF NOT EXISTS vector")

        await conn.execute("""
            CREATE TABLE IF NOT EXISTS corpus_chunks (
                id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
                corpus_hash TEXT    NOT NULL,
                chunk_index INTEGER NOT NULL,
                content     TEXT    NOT NULL,
                embedding   vector(1536)
            )
        """)

        await conn.execute("""
            CREATE TABLE IF NOT EXISTS benchmark_runs (
                id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
                created_at          TIMESTAMPTZ NOT NULL    DEFAULT NOW(),
                status              TEXT        NOT NULL    DEFAULT 'pending'
                                    CHECK (status IN ('pending', 'running', 'completed', 'failed')),
                retrieval_strategy  TEXT        NOT NULL,
                chunker_strategy    TEXT        NOT NULL,
                retrieval_params    JSONB       NOT NULL    DEFAULT '{}',
                chunker_params      JSONB       NOT NULL    DEFAULT '{}',
                compression_enabled BOOLEAN     NOT NULL    DEFAULT FALSE,
                compression_params  JSONB       NOT NULL    DEFAULT '{}',
                corpus_hash         TEXT        NOT NULL,
                question            TEXT        NOT NULL,
                retrieved_chunks    JSONB       NOT NULL    DEFAULT '[]',
                generated_answer    TEXT,
                faithfulness        FLOAT,
                context_utilization FLOAT,
                answer_relevancy    FLOAT,
                latency_ms          FLOAT,
                error_message       TEXT
            )
        """)

        # Composite primary key (fingerprint_hash, date) means one row per
        # hashed fingerprint per calendar day. Old rows from previous days are
        # never updated -- the ON CONFLICT clause only matches today's row.
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS rate_limit_counters (
                fingerprint_hash TEXT NOT NULL,
                date             DATE NOT NULL DEFAULT CURRENT_DATE,
                run_count        INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (fingerprint_hash, date)
            )
        """)


async def corpus_exists(corpus_hash: str) -> bool:
    """
    Return True if at least one chunk exists for the given corpus_hash.

    Used by the ingest endpoint to detect duplicate uploads and by the
    benchmark endpoint to validate that the corpus was successfully ingested
    before attempting retrieval.

    Parameters
    ----------
    corpus_hash : str
        SHA-256 hex digest identifying the uploaded corpus.

    Returns
    -------
    bool
        True if the corpus has at least one stored chunk, False otherwise.
    """
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT 1 FROM corpus_chunks WHERE corpus_hash = $1 LIMIT 1",
            corpus_hash,
        )
    return row is not None


async def store_chunks(
    corpus_hash: str,
    chunks: list[tuple[str, list[float]]],
) -> None:
    """
    Insert all chunks for a corpus in a single batch operation.

    Uses asyncpg's executemany() which sends the INSERT as a server-side
    prepared statement executed once per row. This is significantly faster
    than N individual execute() calls because asyncpg pipelines the rows in
    a single network roundtrip rather than waiting for each row's confirmation
    before sending the next one.

    Parameters
    ----------
    corpus_hash : str
        SHA-256 hex digest identifying the corpus these chunks belong to.
    chunks : list[tuple[str, list[float]]]
        Ordered list of (content, embedding) pairs. chunk_index is assigned
        from the list position (0-based) and preserved for deterministic
        ordering when loading the corpus later.
    """
    pool = await get_pool()
    async with pool.acquire() as conn:
        await conn.executemany(
            """
            INSERT INTO corpus_chunks (corpus_hash, chunk_index, content, embedding)
            VALUES ($1, $2, $3, $4)
            """,
            [
                (corpus_hash, idx, content, embedding)
                for idx, (content, embedding) in enumerate(chunks)
            ],
        )


async def get_chunk_count(corpus_hash: str) -> int:
    """
    Return the number of stored chunks for a given corpus_hash.

    Used by the ingest endpoint when returning early on a duplicate upload
    so the caller receives an accurate chunk count without re-processing.

    Parameters
    ----------
    corpus_hash : str
        SHA-256 hex digest identifying the corpus.

    Returns
    -------
    int
        Number of corpus_chunks rows for this corpus_hash. Zero if none exist.
    """
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT COUNT(*) AS n FROM corpus_chunks WHERE corpus_hash = $1",
            corpus_hash,
        )
    return int(row["n"])


async def load_corpus(corpus_hash: str) -> list[dict]:
    """
    Load all chunks for a corpus from the database in chunk_index order.

    Returns each chunk as a dict in the format expected by retriever
    constructors: chunk_id, content, and embedding as a Python list.

    Parameters
    ----------
    corpus_hash : str
        SHA-256 hex digest identifying the corpus.

    Returns
    -------
    list[dict]
        Ordered list of dicts with keys: chunk_id (str), content (str),
        embedding (list[float]). Empty list if no chunks exist.
    """
    pool = await get_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT id, content, embedding
            FROM corpus_chunks
            WHERE corpus_hash = $1
            ORDER BY chunk_index
            """,
            corpus_hash,
        )
    return [
        {
            "chunk_id": str(row["id"]),
            "content": row["content"],
            # pgvector returns numpy arrays; convert to plain Python list
            # so retriever code can use standard list operations.
            "embedding": list(row["embedding"]),
        }
        for row in rows
    ]


async def increment_run_count(fingerprint_hash: str) -> None:
    """
    Increment the benchmark run counter for today for the given fingerprint.

    Uses INSERT ... ON CONFLICT DO UPDATE so the operation is atomic and
    requires no separate existence check. If no row exists for this
    fingerprint and today's date, a new row is created with run_count=1.
    If a row already exists, its run_count is incremented by 1.

    The composite primary key (fingerprint_hash, date) ensures one counter
    row per fingerprint per calendar day. Yesterday's counter rows are never
    modified and can be cleaned up by a scheduled job later.

    Parameters
    ----------
    fingerprint_hash : str
        SHA-256 hex digest of the combined IP + browser fingerprint string.
    """
    pool = await get_pool()
    async with pool.acquire() as conn:
        await conn.execute(
            """
            INSERT INTO rate_limit_counters (fingerprint_hash, date, run_count)
            VALUES ($1, CURRENT_DATE, 1)
            ON CONFLICT (fingerprint_hash, date)
            DO UPDATE SET run_count = rate_limit_counters.run_count + 1
            """,
            fingerprint_hash,
        )


async def get_run_count(fingerprint_hash: str) -> int:
    """
    Return the number of benchmark runs made today by the given fingerprint.

    Returns 0 if no row exists for today, which is the correct starting state
    for a fingerprint that has not run any benchmarks today.

    Parameters
    ----------
    fingerprint_hash : str
        SHA-256 hex digest of the combined IP + browser fingerprint string.

    Returns
    -------
    int
        Number of runs recorded today. 0 if the fingerprint has no row yet.
    """
    pool = await get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            """
            SELECT run_count FROM rate_limit_counters
            WHERE fingerprint_hash = $1 AND date = CURRENT_DATE
            """,
            fingerprint_hash,
        )
    return int(row["run_count"]) if row is not None else 0
