"""
Base class and registration machinery for LLM providers.

Defines BaseLLMProvider, the abstract class every LLM backend must extend,
and the @register decorator that makes providers auto-discoverable without
hardcoding provider names anywhere in the codebase.

Two providers are currently implemented: openai_provider (used for guest-tier
retrieval and RAGAS judging) and anthropic_provider (available for Tier 2 BYOK
users). Adding a third provider requires only a new module in this directory.
"""

from abc import ABC, abstractmethod

# Global registry mapping provider name strings to their implementing classes.
# Populated at import time when each provider module is imported by registry.py.
registry: dict[str, type["BaseLLMProvider"]] = {}


def register(cls: type["BaseLLMProvider"]) -> type["BaseLLMProvider"]:
    """
    Class decorator that registers an LLM provider in the module-level registry.

    Must be applied after the class body is fully defined so that `cls.name`
    is already set when the decorator runs.

    Parameters
    ----------
    cls : type[BaseLLMProvider]
        The concrete provider class. Must have a `name` class attribute.

    Returns
    -------
    type[BaseLLMProvider]
        The same class, unmodified, so it can still be referenced by name
        in the module where it is defined.
    """
    # Key by cls.name so the benchmark runner can instantiate any provider
    # by the string name it receives from the API request.
    registry[cls.name] = cls
    return cls


class BaseLLMProvider(ABC):
    """
    Abstract base class for all LLM backend integrations.

    Concrete subclasses wrap a specific LLM API (OpenAI, Anthropic, etc.)
    and expose a uniform interface so retrieval strategies and the eval runner
    can call any provider without knowing which SDK is underneath.

    All methods are async because every provider makes outbound HTTP calls
    via httpx, which must not block the FastAPI event loop.
    """

    # Short machine-readable identifier used as the registry key
    # (e.g. "openai", "anthropic").
    name: str

    # Human-readable label shown in the benchmark UI provider selector.
    display_name: str

    @abstractmethod
    async def complete(self, prompt: str) -> str:
        """
        Generate a text completion for the given prompt.

        Used by retrieval strategies that need LLM inference at query time:
        HyDE (generate a hypothetical answer), multi-query (generate query
        variants), and contextual compression (compress a chunk to relevant
        sentences).

        Parameters
        ----------
        prompt : str
            The full prompt string to send to the LLM, including any
            system instructions and user content.

        Returns
        -------
        str
            The model's completion text, with no surrounding whitespace
            trimmed or added by this method.
        """
        ...

    @abstractmethod
    async def embed(self, text: str) -> list[float]:
        """
        Return a dense embedding vector for the given text.

        Used by all dense and hybrid retrieval strategies to convert a query
        (or a hypothetical answer in HyDE) into a vector for cosine similarity
        search against the pgvector index.

        Parameters
        ----------
        text : str
            The text to embed. For retrieval, this is typically the query
            string or a hypothetical answer generated by complete().

        Returns
        -------
        list[float]
            The embedding vector. Dimensionality depends on the model
            (text-embedding-3-small produces 1536 floats).
        """
        ...
